// solid-project/src/components/Navbar.tsx
import { A } from '@solidjs/router';
import type { ParentComponent } from 'solid-js';

type NavItemProps = ParentComponent<{ href: string }>;

const NavItem: NavItemProps = (props) => {
	return (
		<A
			href={props.href}
			class="hover:underline"
			activeClass="text-destructive underline"
		>
			{props.children}
		</A>
	);
};

export const Navbar = () => {
	return (
		<nav class="bg-primary text-primary-foreground py-6 font-bold">
			<div class="container mx-auto flex justify-between">
				<A href="/" class="hover:underline">
					Simply Invoice
				</A>

				<div class="flex gap-12">
					<NavItem href="/companies">Companies</NavItem>
					<NavItem href="/customers">Customers</NavItem>
					<NavItem href="/services">Services</NavItem>
					<NavItem href="/invoices">Invoices</NavItem>
				</div>
			</div>
		</nav>
	);
};

// app/components/Navbar.tsx
import { Link, NavLink } from '@remix-run/react';

import { cn } from '~/lib/utils';

type SideBarLinkProps = {
	to: string;
	children: React.ReactNode;
};

function NavItem({ to, children }: SideBarLinkProps) {
	return (
		<NavLink
			to={to}
			className={({ isActive }) =>
				cn('hover:underline', isActive && 'text-destructive underline')
			}
		>
			{children}
		</NavLink>
	);
}

export function Navbar() {
	return (
		<nav className="bg-primary py-6 font-bold text-primary-foreground">
			<div className="container mx-auto flex justify-between">
				<Link className="hover:underline" to="/">
					Simply Invoice
				</Link>

				<div className="flex gap-12">
					<NavItem to="/invoices">Invoices</NavItem>
					<NavItem to="/companies">Companies</NavItem>
					<NavItem to="/customers">Customers</NavItem>
					<NavItem to="/services">Services</NavItem>
				</div>
			</div>
		</nav>
	);
}
