// src/renderer.tsx
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { RouterProvider } from "react-router";
import { router } from "~/router";

const root = document.getElementById("root");
if (!root) {
	throw new Error("Root element not found");
}

createRoot(root).render(
	<StrictMode>
		<RouterProvider router={router} />
	</StrictMode>,
);

// electron-solid-starter/src/renderer/index.tsx
import { Router } from '@solidjs/router';
import { render } from 'solid-js/web';

import { App } from './modules/App';

const rootElement = document.getElementById('root');

if (!rootElement) {
  throw new Error('Root element not found');
}

render(
  () => (
    <Router>
      <App />
    </Router>
  ),
  rootElement
);
